import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from '@/components/modals/ThemeProvider';
import { experimental__simple } from '@clerk/themes';
import Navbar from '@/components/navbar';

const dm = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={dm.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
